### ISSUE TITLE
After loading PSX core, MiSTer display is pushed left and slightly up.  Persistent with all cores until power cycle.

### ISSUE THREAD

**Issue by teknomedic** [MiSTer-devel/PSX_MiSTer#96]
After running the PSX core (even without running a game) the MiSTer begins displaying all video output shifted to the left.  This is persistent on all cores (Including PSX) once triggered.  It would be difficult to notice if you keep all content in 4:3 mode on a small display.

On my 75" LCD display this moves content to the left several inches and cuts off text if running something like the Update_All script.  I also noted this will cause visual issues in other cores as well.  When I ran the SNES core and changed aspect ratio I noted graphical issues in areas that would normally be "hidden" as if the core was attempting to fill in the area with duplicated pixels.

**Only power cycling the MiSTer fixes this**
Power cycling my display and AVR do not help.  Switching cores does not help.  Resetting/rebooting MiSTer does not help.

**Comment by birdybro** [comment]
This is related to the VIC and HDMI_Config changes. This should be fixed in the next release of Main_MiSTer that contains these changes --> https://github.com/MiSTer-devel/Main_MiSTer/commit/b1271ad983f39d220b6a1ac95db24e22ad99209f

**Comment by neodivad** [comment]
I ran into the same issue. After running the PSX core the picture would shift left and up slightly, sometimes with a purple line at the bottom of screen. It affected all cores and wouldn't go away after rebooting. The issue disappeared only after completely powering off. 

After the most recent updates on May 17 the issue persists even after my MiSter was off all night. As soon as it was powered on today I noticed the "tv static" background had a garbled mess on the right side of the screen and the text was cut off during the update all script.

**Comment by teknomedic** [comment]
Latest HDMI changes have made the issue worse!  Now my MiSTer is also permanently stuck with the video off center.  As "neodivad" mentions... now power cycling the MiSTer no longer fixes it. ha.  I assume this might be related to the recent HDMI adjustments made in the MiSTer main?... as described here:

[https://misterfpga.org/viewtopic.php?p=51569#p51569](https://misterfpga.org/viewtopic.php?p=51569#p51569)
"Main:
- Move HDMI output configuration to HPS for better flexibility and future options.
- video: make HDMI game mode optional (in MiSTer.ini).
- video: associate a VIC mode with the predefined video modes (Martin Donlon).
- audio: fix core volume control.
- SNES: support for MSU1 audio (based on concept from Karl Lurman and ElectronAsh) and data/video."

**Comment by wickerwaka** [comment]
Can you share your MiSTer.ini and specify what TV model you are using?

**Comment by wickerwaka** [comment]
Please try with this MiSTer binary: https://github.com/MiSTer-unstable-nightlies/Main_MiSTer/releases/download/unstable-builds/MiSTer_unstable_20220520_161afb

**Comment by neodivad** [comment]
How do I try that unstable build? I looked at birdybro's instructions above but don't see a MiSTer file in /media/fat just in the main directory.

**Comment by birdybro** [comment]
Yes, this is the file I'm referring to.

![image](https://user-images.githubusercontent.com/16388068/169672087-f26403d7-f0a8-4247-8273-8d999fbcf094.png)

You will see it as being in `/media/fat/` if you are FTP or SCP connected to your MiSTer. If you are doing samba, it will be in `//mister/sdcard/`. If you are have taken your sdcard out and plugged it into your computer, it will be just the root of that directory.

**Comment by neodivad** [comment]
Thanks for clearing that up.

I tried the May 20 build but it did not solve the issue. The screen is still off center and shifted left, sometimes with a purple line across the bottom.

I also tried updating another MiSTer sd card to the May 17 release and as soon as it rebooted I could see the tv static background was shifted left. Using the newest build didn't solve the issue on this card either.

**Comment by teknomedic** [comment]
Sorry about delay, had a messed up work schedule.

okay...so...
I replaced my mister.ini with a fresh copy, same issue.  I compared my ini against a fresh copy and using an online file/text compare program... There are no changes to my ini vs a fresh copy.

I also tried a fresh copy of the mister menu.rbf with no changes.

I've also tried switching to PAL mode on my AVR and TV with no change... It remains shifted left.

I also tried the recent unstable build suggested above.  No changes.  HOWEVER... I tried an older revision (220511) and the menu is back to normal again.  So what ever is causing this is in the main "MiSTer" file.  With menu fixed on older revision, both my AVR and TV report getting a 720p/60hz signal (SEE BELOW FOR MORE)... 


Extra information that might be helpful... 

I'm running on a Denon X3300W AVR with a Vizio P75-F1 display using HDMI.  Currently my AVR and TV both report they are getting a 720p/60hz signal from the MiSTer when menu is displaying incorrectly. 

My AVR also allows HDMI pass through when it's in standby and I've noticed that when I put it into standby, the MiSTer CORRECTLY displays again until I wake-up the AVR.  HOWEVER.... My display still reports it is getting a 720p/60hz signal from the MiSTer.  This makes me wonder if the mister has become locked to a slightly off timing... As a likely bad example...  perhaps after running PSX the mister gets locked to something like 59.7hz that my AVR doesn't notice as not 60hz and still processes at 60hz (pushing the display left) but my TV recognizes as 59.7hz and correctly adjusts itself to display correctly when the AVR is removed from the setup.

This also suggests that not everyone will see this issue depending on their equipment's ability to correctly identify and process this slightly off frequency.

Finally the issue is clearly temporary (until power cycle) in older revisions of mister and yet becomes "stuck" in newer revisions so hopefully that gives a limited area to look at to find a fix.

**Comment by teknomedic** [comment]
Additional... After my last post I found another core that can trigger this issue.  I'm using revision 220511 to test (since I can fix it with power cycling).  The original GameBoy core will trigger the same issue on loading the core without needing to run a game.  I used this core as a test using the hypothesis that it's related to resolution/refresh rate of the core running.  NES and SNES cores did not trigger the issue.

**Comment by teknomedic** [comment]
Experimental FIX available in the MiSTer Discord from Wickerwaka here..
https://discord.com/channels/647909397477195803/806759728885006356

The file provided by Wickerwaka fixed both the displaying left issue as well as getting no video in 1080p mode in both PSX and GameBoy cores I noted above.  Hopefully the update will be placed into a new MiSTer update soon.

**Comment by neodivad** [comment]
That fix is also working for me. The screen is no longer shifted left and the PSX core is no longer triggering the issue. 

It does look like this was related to my receiver being a Denon, AVR-X3400H.
